export const data = {
  products: [
    {
      productAdminUserUID: "",
      title: "Funko POP! Animation: Dragon Ball Super Gohan Metallic",
      brand: "Funko",
      price: 11.99,
      currency: "USD",
      product_type: "New",
      stock: 3,
      thumb: "./assets/product-1.jpg",
      image: "./assets/product-1.jpg",
      category: "Funko",
      description: "Goku’s eldest son, Gohan, joins his father in the fight to defend Earth from destruction.",
      completeDescription:
        "Goku’s eldest son, Gohan, joins his father in the fight to defend Earth from destruction. Build the Dragon Team in your Dragon Ball Super collection with this GameStop exclusive Metallic Pop! Gohan.Vinyl figure is approximately 3.75-inches tall.",
      rate: 3.7917,
      review: 48,
      screenshots: "",
      id: "31889272-b082-511e-b7f6-f8ec7181a7f6",
      createdDate: "21/12/2021 11:48:15",
    },
    {
      productAdminUserUID: "",
      title: "Funko POP! Animation: Dragon Ball Super Gohan Metallic.",
      brand: "Funko",
      price: 11.99,
      currency: "USD",
      product_type: "New",
      stock: 0,
      thumb: "./assets/product-2.jpg",
      image: "./assets/product-1.jpg",
      category: "Funko",
      description: "Goku’s eldest son, Gohan, joins his father in the fight to defend Earth from destruction.",
      completeDescription:
        "Goku’s eldest son, Gohan, joins his father in the fight to defend Earth from destruction. Build the Dragon Team in your Dragon Ball Super collection with this GameStop exclusive Metallic Pop! Gohan.Vinyl figure is approximately 3.75-inches tall.",
      rate: 3.7917,
      review: 48,
      screenshots: "",
      id: "31889272-b082-511e-b7f6",
      createdDate: "21/12/2021 11:48:15",
    },
    {
      productAdminUserUID: "",
      title: "Funko POP! Animation: Dragon Ball Super Gohan Metallic.",
      brand: "Funko",
      price: 11.99,
      currency: "USD",
      product_type: "New",
      stock: 10,
      thumb: "./assets/product-3.jpg",
      image: "./assets/product-1.jpg",
      category: "Funko",
      description: "Goku’s eldest son, Gohan, joins his father in the fight to defend Earth from destruction.",
      completeDescription:
        "Goku’s eldest son, Gohan, joins his father in the fight to defend Earth from destruction. Build the Dragon Team in your Dragon Ball Super collection with this GameStop exclusive Metallic Pop! Gohan.Vinyl figure is approximately 3.75-inches tall.",
      rate: 3.7917,
      review: 48,
      screenshots: "",
      id: "31889272-b082-511e-f8ec7181a7f6",
      createdDate: "21/12/2021 11:48:15",
    },
    {
      productAdminUserUID: "",
      title: "Funko POP! Animation: Dragon Ball Super Gohan Metallic.",
      brand: "Funko",
      price: 11.99,
      currency: "USD",
      product_type: "New",
      stock: 100,
      thumb: "./assets/product.jpg",
      image: "./assets/product-1.jpg",
      category: "Funko",
      description: "Goku’s eldest son, Gohan, joins his father in the fight to defend Earth from destruction.",
      completeDescription:
        "Goku’s eldest son, Gohan, joins his father in the fight to defend Earth from destruction. Build the Dragon Team in your Dragon Ball Super collection with this GameStop exclusive Metallic Pop! Gohan.Vinyl figure is approximately 3.75-inches tall.",
      rate: 3.7917,
      review: 48,
      screenshots: "",
      id: "31889272-b082-b7f6-f8ec7181a7f6",
      createdDate: "21/12/2021 11:48:15",
    },
    {
      productAdminUserUID: "",
      title: "Funko POP! Animation: Dragon Ball Super Gohan Metallic",
      brand: "Funko",
      price: 11.99,
      currency: "USD",
      product_type: "New",
      stock: 3,
      thumb: "./assets/product-1.jpg",
      image: "./assets/product-1.jpg",
      category: "Funko",
      description: "Goku’s eldest son, Gohan, joins his father in the fight to defend Earth from destruction.",
      completeDescription:
        "Goku’s eldest son, Gohan, joins his father in the fight to defend Earth from destruction. Build the Dragon Team in your Dragon Ball Super collection with this GameStop exclusive Metallic Pop! Gohan.Vinyl figure is approximately 3.75-inches tall.",
      rate: 3.7917,
      review: 48,
      screenshots: "",
      id: "31889272-511e-b7f6-f8ec7181a7f6",
      createdDate: "21/12/2021 11:48:15",
    },
    {
      productAdminUserUID: "",
      title: "Funko POP! Animation: Dragon Ball Super Gohan Metallic.",
      brand: "Funko",
      price: 11.99,
      currency: "USD",
      product_type: "New",
      stock: 0,
      thumb: "./assets/product-2.jpg",
      image: "./assets/product-1.jpg",
      category: "Funko",
      description: "Goku’s eldest son, Gohan, joins his father in the fight to defend Earth from destruction.",
      completeDescription:
        "Goku’s eldest son, Gohan, joins his father in the fight to defend Earth from destruction. Build the Dragon Team in your Dragon Ball Super collection with this GameStop exclusive Metallic Pop! Gohan.Vinyl figure is approximately 3.75-inches tall.",
      rate: 3.7917,
      review: 48,
      screenshots: "",
      id: "b082-511e-b7f6-f8ec7181a7f6",
      createdDate: "21/12/2021 11:48:15",
    },
    {
      productAdminUserUID: "",
      title: "Funko POP! Animation: Dragon Ball Super Gohan Metallic.",
      brand: "Funko",
      price: 11.99,
      currency: "USD",
      product_type: "New",
      stock: 10,
      thumb: "./assets/product-3.jpg",
      image: "./assets/product-1.jpg",
      category: "Funko",
      description: "Goku’s eldest son, Gohan, joins his father in the fight to defend Earth from destruction.",
      completeDescription:
        "Goku’s eldest son, Gohan, joins his father in the fight to defend Earth from destruction. Build the Dragon Team in your Dragon Ball Super collection with this GameStop exclusive Metallic Pop! Gohan.Vinyl figure is approximately 3.75-inches tall.",
      rate: 3.7917,
      review: 48,
      screenshots: "",
      id: "318-89272-b082-511e-b7f6-f8ec7181a7f6",
      createdDate: "21/12/2021 11:48:15",
    },
    {
      productAdminUserUID: "",
      title: "Funko POP! Animation: Dragon Ball Super Gohan Metallic.",
      brand: "Funko",
      price: 11.99,
      currency: "USD",
      product_type: "New",
      stock: 100,
      thumb: "./assets/product-4.jpg",
      image: "./assets/product-1.jpg",
      category: "Funko",
      description: "Goku’s eldest son, Gohan, joins his father in the fight to defend Earth from destruction.",
      completeDescription:
        "Goku’s eldest son, Gohan, joins his father in the fight to defend Earth from destruction. Build the Dragon Team in your Dragon Ball Super collection with this GameStop exclusive Metallic Pop! Gohan.Vinyl figure is approximately 3.75-inches tall.",
      rate: 3.7917,
      review: 48,
      screenshots: "",
      id: "31-889-272-b082-511e-b7f6-f8ec7181a7f6",
      createdDate: "21/12/2021 11:48:15",
    },
  ],
};
